var namespace_mih_stat_library_test_1_1_calculators_tests =
[
    [ "BitFrequencyCalculatorTest", "class_mih_stat_library_test_1_1_calculators_tests_1_1_bit_frequency_calculator_test.html", "class_mih_stat_library_test_1_1_calculators_tests_1_1_bit_frequency_calculator_test" ]
];