//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MihStatLibraryTest {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataFiles() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MihStatLibraryTest.DataFiles", typeof(DataFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\00000000_131MB.
        /// </summary>
        internal static string File00000000_131MB {
            get {
                return ResourceManager.GetString("File00000000_131MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\00001111_131MB.
        /// </summary>
        internal static string File00001111_131MB {
            get {
                return ResourceManager.GetString("File00001111_131MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\01010101_131MB.
        /// </summary>
        internal static string File01010101_131MB {
            get {
                return ResourceManager.GetString("File01010101_131MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\10101010_131MB.
        /// </summary>
        internal static string File10101010_131MB {
            get {
                return ResourceManager.GetString("File10101010_131MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\1110000_131MB.
        /// </summary>
        internal static string File11110000_131MB {
            get {
                return ResourceManager.GetString("File11110000_131MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\11110000_1KB.
        /// </summary>
        internal static string File11110000_1KB {
            get {
                return ResourceManager.GetString("File11110000_1KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\11110000_1MB.
        /// </summary>
        internal static string File11110000_1MB {
            get {
                return ResourceManager.GetString("File11110000_1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\11110000_5MB.
        /// </summary>
        internal static string File11110000_5MB {
            get {
                return ResourceManager.GetString("File11110000_5MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\11111111_131MB.
        /// </summary>
        internal static string File11111111_131MB {
            get {
                return ResourceManager.GetString("File11111111_131MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\12345678etc_256B.
        /// </summary>
        internal static string File12345678etc256B {
            get {
                return ResourceManager.GetString("File12345678etc256B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\random_128MB.
        /// </summary>
        internal static string FileRandom128MB {
            get {
                return ResourceManager.GetString("FileRandom128MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..\..\..\Resources\random_1GB.
        /// </summary>
        internal static string FileRandom1GB {
            get {
                return ResourceManager.GetString("FileRandom1GB", resourceCulture);
            }
        }
    }
}
