.TH "obj/Release/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/Release/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
