.TH "BlockData/BlockDataRandomSource.cs" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockData/BlockDataRandomSource.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMihStatLibrary\&.BlockData\&.BlockDataRandomSource\fP"
.br
.RI "Источник получения случайных данных\&. Случайная последовательность получается путем XOR-а определенного количества случайных значений\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBMihStatLibrary\fP"
.br
.ti -1c
.RI "namespace \fBMihStatLibrary\&.BlockData\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
