.TH "Counters/CountersExceptions.cs" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Counters/CountersExceptions.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMihStatLibrary\&.Counters\&.OnesCounterException\fP"
.br
.RI "Исключение, возникающее при попытке посчитать количество единиц на гистограмме частот со смещением отличным от размерности "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBMihStatLibrary\fP"
.br
.ti -1c
.RI "namespace \fBMihStatLibrary\&.Counters\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
