.TH "Содержание директории obj/Debug/net8.0" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории obj/Debug/net8.0
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fB\&.NETCoreApp,Version=v8\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "файл \fBMihStatLibrary\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "файл \fBMihStatLibrary\&.GlobalUsings\&.g\&.cs\fP"
.br
.in -1c
