.TH "Содержание директории Calculators" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории Calculators
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBCalculatorsExceptions\&.cs\fP"
.br
.ti -1c
.RI "файл \fBOnesCalculator\&.cs\fP"
.br
.ti -1c
.RI "файл \fBProbabilityCalculator\&.cs\fP"
.br
.in -1c
