.TH "Histogram/HistogramExceptions.cs" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Histogram/HistogramExceptions.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMihStatLibrary\&.Histogram\&.ReduceException\fP"
.br
.RI "Исключение, возникающее при попытке пересчитать гистограмму частот на меньшую размерность "
.ti -1c
.RI "class \fBMihStatLibrary\&.Histogram\&.InvalidShiftException\fP"
.br
.RI "Исключение, возникающее при попытке задать сдвиг больше размерности "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBMihStatLibrary\fP"
.br
.ti -1c
.RI "namespace \fBMihStatLibrary\&.Histogram\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
