.TH "Data/IBlockDataSource.cs" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data/IBlockDataSource.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "interface \fBMihStatLibrary\&.Data\&.IBlockDataSource\fP"
.br
.RI "Интерфейс источника получения блока данных "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBMihStatLibrary\fP"
.br
.ti -1c
.RI "namespace \fBMihStatLibrary\&.Data\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
