.TH "MihStatLibrary.Calculators.ProbabilityCalculator" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.Calculators.ProbabilityCalculator \- Класс Вычислителя вероятностей бит 1 и 0 в данных  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBProbabilityCalculator\fP ()"
.br
.RI "Конструктор класса вычислителя вероятностей бит 1 и 0 в данных "
.ti -1c
.RI "async void \fBCalculateAsync\fP (string fileName)"
.br
.RI "Ассинхронная функция рассчета вероятностей 1 и 0 в файле "
.ti -1c
.RI "void \fBCalculate\fP (string fileName)"
.br
.RI "Функция рассчета вероятностей 1 и 0 в файле "
.ti -1c
.RI "void \fBCalculate\fP (\fBFreqHistogram\fP freqHistogram)"
.br
.RI "Функция рассчета вероятностей 1 и 0 по гистограмме частот\&. СМЕЩЕНИЕ ДОЛЖНО БЫТЬ РАВНО РАЗМЕРНОСТИ! ЕСЛИ РАЗМЕР ФАЙЛА В БИТАХ НЕ КРАТЕН РАЗМЕРНОСТИ ГИСТОГРАММЫ ЧАСТОТ, БИТЫ, НЕ ОБСЧИТАННЫЕ ГИСТОГРАММОЙ, НЕ УЧИТЫВАЮТСЯ! "
.in -1c
.SS "Свойства"

.in +1c
.ti -1c
.RI "double \fBProbabilityOne\fP\fR [get]\fP"
.br
.RI "Вероятность бита 1 в данных "
.ti -1c
.RI "double \fBProbabilityZero\fP\fR [get]\fP"
.br
.RI "Вероятность бита 0 в данных "
.in -1c
.SH "Подробное описание"
.PP 
Класс Вычислителя вероятностей бит 1 и 0 в данных 
.PP
См\&. определение в файле \fBProbabilityCalculator\&.cs\fP строка \fB15\fP
.SH "Конструктор(ы)"
.PP 
.SS "MihStatLibrary\&.Calculators\&.ProbabilityCalculator\&.ProbabilityCalculator ()"

.PP
Конструктор класса вычислителя вероятностей бит 1 и 0 в данных 
.PP
См\&. определение в файле \fBProbabilityCalculator\&.cs\fP строка \fB33\fP
.SH "Методы"
.PP 
.SS "void MihStatLibrary\&.Calculators\&.ProbabilityCalculator\&.Calculate (\fBFreqHistogram\fP freqHistogram)"

.PP
Функция рассчета вероятностей 1 и 0 по гистограмме частот\&. СМЕЩЕНИЕ ДОЛЖНО БЫТЬ РАВНО РАЗМЕРНОСТИ! ЕСЛИ РАЗМЕР ФАЙЛА В БИТАХ НЕ КРАТЕН РАЗМЕРНОСТИ ГИСТОГРАММЫ ЧАСТОТ, БИТЫ, НЕ ОБСЧИТАННЫЕ ГИСТОГРАММОЙ, НЕ УЧИТЫВАЮТСЯ! 
.PP
\fBАргументы\fP
.RS 4
\fIfreqHistogram\fP Гистограмма частот\&. СМЕЩЕНИЕ ДОЛЖНО БЫТЬ РАВНО РАЗМЕРНОСТИ!
.RE
.PP
\fBИсключения\fP
.RS 4
\fIProbabilityCalculatorException\fP Попытка посчитать количество единиц на гистограмме с разным значением размерности и смещения
.RE
.PP

.PP
См\&. определение в файле \fBProbabilityCalculator\&.cs\fP строка \fB118\fP
.SS "void MihStatLibrary\&.Calculators\&.ProbabilityCalculator\&.Calculate (string fileName)"

.PP
Функция рассчета вероятностей 1 и 0 в файле 
.PP
\fBАргументы\fP
.RS 4
\fIfileName\fP Имя файла
.RE
.PP

.PP
См\&. определение в файле \fBProbabilityCalculator\&.cs\fP строка \fB97\fP
.SS "async void MihStatLibrary\&.Calculators\&.ProbabilityCalculator\&.CalculateAsync (string fileName)"

.PP
Ассинхронная функция рассчета вероятностей 1 и 0 в файле 
.PP
\fBАргументы\fP
.RS 4
\fIfileName\fP Имя файла
.RE
.PP

.PP
См\&. определение в файле \fBProbabilityCalculator\&.cs\fP строка \fB69\fP
.SH "Полный список свойств"
.PP 
.SS "double MihStatLibrary\&.Calculators\&.ProbabilityCalculator\&.ProbabilityOne\fR [get]\fP"

.PP
Вероятность бита 1 в данных 
.PP
См\&. определение в файле \fBProbabilityCalculator\&.cs\fP строка \fB23\fP
.SS "double MihStatLibrary\&.Calculators\&.ProbabilityCalculator\&.ProbabilityZero\fR [get]\fP"

.PP
Вероятность бита 0 в данных 
.PP
См\&. определение в файле \fBProbabilityCalculator\&.cs\fP строка \fB28\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
