.TH "MihStatLibrary.Data.BlockData" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.Data.BlockData \- Класс для получения данных блоками  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBBlockData\fP (\fBIBlockDataSource\fP blockDataSource)"
.br
.RI "Создавет экземпляр класса "
.ti -1c
.RI "void \fBGetBlockData\fP (int szBlock)"
.br
.RI "Заполняет блок данными из источника "
.in -1c
.SS "Свойства"

.in +1c
.ti -1c
.RI "int \fBSzBlockData\fP\fR [get]\fP"
.br
.RI "Размер данных в блоке "
.ti -1c
.RI "byte?[] \fBData\fP\fR [get]\fP"
.br
.RI "Массив, хранящий полученный блок данных "
.in -1c
.SH "Подробное описание"
.PP 
Класс для получения данных блоками 
.PP
См\&. определение в файле \fBBlockData\&.cs\fP строка \fB6\fP
.SH "Конструктор(ы)"
.PP 
.SS "MihStatLibrary\&.Data\&.BlockData\&.BlockData (\fBIBlockDataSource\fP blockDataSource)"

.PP
Создавет экземпляр класса 
.PP
\fBАргументы\fP
.RS 4
\fIblockDataSource\fP Источник данных
.RE
.PP

.PP
См\&. определение в файле \fBBlockData\&.cs\fP строка \fB26\fP
.SH "Методы"
.PP 
.SS "void MihStatLibrary\&.Data\&.BlockData\&.GetBlockData (int szBlock)"

.PP
Заполняет блок данными из источника 
.PP
\fBАргументы\fP
.RS 4
\fIszBlock\fP Размер запрашиваемого количества данных
.RE
.PP

.PP
См\&. определение в файле \fBBlockData\&.cs\fP строка \fB35\fP
.SH "Полный список свойств"
.PP 
.SS "byte? [] MihStatLibrary\&.Data\&.BlockData\&.Data\fR [get]\fP"

.PP
Массив, хранящий полученный блок данных 
.PP
См\&. определение в файле \fBBlockData\&.cs\fP строка \fB20\fP
.SS "int MihStatLibrary\&.Data\&.BlockData\&.SzBlockData\fR [get]\fP"

.PP
Размер данных в блоке 
.PP
См\&. определение в файле \fBBlockData\&.cs\fP строка \fB15\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
