.TH "MihStatLibrary.BlockData" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.BlockData
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBBlockData\fP"
.br
.RI "Класс для получения данных блоками "
.ti -1c
.RI "class \fBBlockDataFileSource\fP"
.br
.RI "Источник получения данных из файла "
.ti -1c
.RI "class \fBBlockDataRandomSource\fP"
.br
.RI "Источник получения случайных данных\&. Случайная последовательность получается путем XOR-а определенного количества случайных значений\&. "
.ti -1c
.RI "interface \fBIBlockDataSource\fP"
.br
.RI "Интерфейс источника получения блока данных "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
