.TH "MihStatLibrary.Calculators.OnesCalculatorException" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.Calculators.OnesCalculatorException \- Исключение, возникающее при попытке посчитать количество единиц на гистограмме частот со смещением отличным от размерности  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Exception\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBOnesCalculatorException\fP (string pMessage)"
.br
.RI "Исключение, возникающее при попытке посчитать количество единиц на гистограмме частот со смещением отличным от размерности "
.in -1c
.SH "Подробное описание"
.PP 
Исключение, возникающее при попытке посчитать количество единиц на гистограмме частот со смещением отличным от размерности 
.PP
См\&. определение в файле \fBCalculatorsExceptions\&.cs\fP строка \fB12\fP
.SH "Конструктор(ы)"
.PP 
.SS "MihStatLibrary\&.Calculators\&.OnesCalculatorException\&.OnesCalculatorException (string pMessage)"

.PP
Исключение, возникающее при попытке посчитать количество единиц на гистограмме частот со смещением отличным от размерности 
.PP
См\&. определение в файле \fBCalculatorsExceptions\&.cs\fP строка \fB17\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
