.TH "MihStatLibrary.Counters" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.Counters
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBOnesCounter\fP"
.br
.RI "Класс подсчета количества единичных бит "
.ti -1c
.RI "class \fBOnesCounterException\fP"
.br
.RI "Исключение, возникающее при попытке посчитать количество единиц на гистограмме частот со смещением отличным от размерности "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
