.TH "MihStatLibrary.Tables.ReduceException" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.Tables.ReduceException \- Исключение, возникающее при попытке пересчитать маркировочную таблицу на меньшую размерность  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Exception\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBReduceException\fP (string pMessage)"
.br
.RI "Исключение, возникающее при попытке задать сдвиг больше размерности "
.in -1c
.SH "Подробное описание"
.PP 
Исключение, возникающее при попытке пересчитать маркировочную таблицу на меньшую размерность 
.PP
См\&. определение в файле \fBMarkTableExceptions\&.cs\fP строка \fB12\fP
.SH "Конструктор(ы)"
.PP 
.SS "MihStatLibrary\&.Tables\&.ReduceException\&.ReduceException (string pMessage)"

.PP
Исключение, возникающее при попытке задать сдвиг больше размерности 
.PP
См\&. определение в файле \fBMarkTableExceptions\&.cs\fP строка \fB17\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
