.TH "MihStatLibrary.Calculators" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.Calculators
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBBitFrequencyCalculator\fP"
.br
.RI "Класс вычислителя оценки вероятностей бит 1 и 0 в данных "
.ti -1c
.RI "class \fBBitFrequencyCalculatorException\fP"
.br
.RI "Исключение, возникающее при попытке посчитать оценки вероятностей бит 1 и 0\&. "
.ti -1c
.RI "class \fBOnesCalculator\fP"
.br
.RI "Класс подсчета количества единичных бит "
.ti -1c
.RI "class \fBOnesCalculatorException\fP"
.br
.RI "Исключение, возникающее при попытке посчитать количество единиц на маркировочной таблице со смещением отличным от размерности "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
