.TH "MihStatLibrary.Calculators.ProbabilityCalculatorException" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.Calculators.ProbabilityCalculatorException \- Исключение, возникающее при попытке посчитать вероятность битов 1 и 0\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Exception\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBProbabilityCalculatorException\fP (string pMessage)"
.br
.RI "Исключение, возникающее при попытке посчитать вероятность битов 1 и 0\&. "
.in -1c
.SH "Подробное описание"
.PP 
Исключение, возникающее при попытке посчитать вероятность битов 1 и 0\&. 
.PP
См\&. определение в файле \fBCalculatorsExceptions\&.cs\fP строка \fB23\fP
.SH "Конструктор(ы)"
.PP 
.SS "MihStatLibrary\&.Calculators\&.ProbabilityCalculatorException\&.ProbabilityCalculatorException (string pMessage)"

.PP
Исключение, возникающее при попытке посчитать вероятность битов 1 и 0\&. 
.PP
См\&. определение в файле \fBCalculatorsExceptions\&.cs\fP строка \fB28\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
