.TH "MihStatLibrary.Histogram.FreqHistogram" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.Histogram.FreqHistogram \- Класс истограммы частот  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBFreqHistogram\fP (int dimension)"
.br
.RI "Конструктор класса гистограммы частот без зацепления "
.ti -1c
.RI "\fBFreqHistogram\fP (int dimension, int szShift)"
.br
.RI "Конструктор класса гистограммы частот с зацеплением "
.ti -1c
.RI "void \fBCalculate\fP (\fBBlockData\fP data)"
.br
.RI "Подсчет гистограммы частот по блоку данных "
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Обнуление гистограммы частот "
.ti -1c
.RI "void \fBCalculate\fP (string fileName)"
.br
.RI "Подсчет гистограммы частот по данным файла "
.ti -1c
.RI "void \fBReduce\fP (\fBFreqHistogram\fP destHistogram)"
.br
.RI "Функция пересчета гистограммы частот в гистограмму с меньшей размерностью векторов\&. ФУНКЦИЯ РАБОТАЕТ ТОЛЬКО СО СМЕЩЕНИЕМ 1! "
.ti -1c
.RI "\fBFreqHistogram\fP \fBReduce\fP (int pDestDimension)"
.br
.RI "Функция создания гистограммы частот на основании гистограммы частот большей размерности\&. ФУНКЦИЯ РАБОТАЕТ ТОЛЬКО СО СМЕЩЕНИЕМ 1! "
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.RI "Глубокое сравнение двух экземпляров FreqHistogram "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "Вычисление hash объекта FreqHistogram "
.in -1c
.SS "Свойства"

.in +1c
.ti -1c
.RI "long[] \fBHistogram\fP\fR [get]\fP"
.br
.RI "Гистограмма частот "
.ti -1c
.RI "int \fBDimension\fP\fR [get]\fP"
.br
.RI "Размерность гистограммы частот "
.ti -1c
.RI "long \fBNmVectors\fP\fR [get]\fP"
.br
.RI "Количество учтенных последовательностей "
.ti -1c
.RI "int \fBSzShift\fP\fR [get]\fP"
.br
.RI "Смещение гистограммы частот "
.in -1c
.SS "События"

.in +1c
.ti -1c
.RI "EventHandler< string >? \fBProcessChanged\fP = null"
.br
.RI "Событие изменения процесса обсчитывания "
.ti -1c
.RI "EventHandler< int >? \fBProgressChanged\fP = null"
.br
.RI "Событие изменения прогресса обсчитывания "
.in -1c
.SH "Подробное описание"
.PP 
Класс истограммы частот 
.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB15\fP
.SH "Конструктор(ы)"
.PP 
.SS "MihStatLibrary\&.Histogram\&.FreqHistogram\&.FreqHistogram (int dimension)"

.PP
Конструктор класса гистограммы частот без зацепления 
.PP
\fBАргументы\fP
.RS 4
\fIdimension\fP Размерность векторов гистограммы
.RE
.PP

.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB62\fP
.SS "MihStatLibrary\&.Histogram\&.FreqHistogram\&.FreqHistogram (int dimension, int szShift)"

.PP
Конструктор класса гистограммы частот с зацеплением 
.PP
\fBАргументы\fP
.RS 4
\fIdimension\fP Размерность векторов гистограммы
.br
\fIszShift\fP Размер смещения
.RE
.PP
\fBИсключения\fP
.RS 4
\fIInvalidShiftException\fP Попытка задать смещение больше размерности
.RE
.PP

.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB79\fP
.SH "Методы"
.PP 
.SS "void MihStatLibrary\&.Histogram\&.FreqHistogram\&.Calculate (\fBBlockData\fP data)"

.PP
Подсчет гистограммы частот по блоку данных 
.PP
\fBАргументы\fP
.RS 4
\fIdata\fP Блок данных
.RE
.PP

.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB90\fP
.SS "void MihStatLibrary\&.Histogram\&.FreqHistogram\&.Calculate (string fileName)"

.PP
Подсчет гистограммы частот по данным файла 
.PP
\fBАргументы\fP
.RS 4
\fIfileName\fP Имя файла
.RE
.PP

.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB130\fP
.SS "void MihStatLibrary\&.Histogram\&.FreqHistogram\&.Clear ()"

.PP
Обнуление гистограммы частот 
.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB118\fP
.SS "override bool MihStatLibrary\&.Histogram\&.FreqHistogram\&.Equals (object? obj)"

.PP
Глубокое сравнение двух экземпляров FreqHistogram 
.PP
\fBАргументы\fP
.RS 4
\fIobj\fP Экземпляр для сравнения
.RE
.PP
\fBВозвращает\fP
.RS 4
Результат сравнения
.RE
.PP

.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB240\fP
.SS "override int MihStatLibrary\&.Histogram\&.FreqHistogram\&.GetHashCode ()"

.PP
Вычисление hash объекта FreqHistogram 
.PP
\fBВозвращает\fP
.RS 4
Hash объекта FreqHistogram
.RE
.PP

.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB263\fP
.SS "void MihStatLibrary\&.Histogram\&.FreqHistogram\&.Reduce (\fBFreqHistogram\fP destHistogram)"

.PP
Функция пересчета гистограммы частот в гистограмму с меньшей размерностью векторов\&. ФУНКЦИЯ РАБОТАЕТ ТОЛЬКО СО СМЕЩЕНИЕМ 1! 
.PP
\fBАргументы\fP
.RS 4
\fIdestHistogram\fP Гистограмма, куда будут записаны пересчитанные значения\&. смещение должно быть равным 1!
.RE
.PP
\fBИсключения\fP
.RS 4
\fIReduceException\fP Попытка пересчитать гистограмму на большую размерность или смещения гистограм не равны 1
.RE
.PP

.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB152\fP
.SS "\fBFreqHistogram\fP MihStatLibrary\&.Histogram\&.FreqHistogram\&.Reduce (int pDestDimension)"

.PP
Функция создания гистограммы частот на основании гистограммы частот большей размерности\&. ФУНКЦИЯ РАБОТАЕТ ТОЛЬКО СО СМЕЩЕНИЕМ 1! 
.PP
\fBАргументы\fP
.RS 4
\fIpDestDimension\fP Размерность новой гистограммы
.RE
.PP
\fBВозвращает\fP
.RS 4
Новая гистограмма с пересчитанными значениями и сдвигом 1
.RE
.PP

.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB184\fP
.SH "Полный список свойств"
.PP 
.SS "int MihStatLibrary\&.Histogram\&.FreqHistogram\&.Dimension\fR [get]\fP"

.PP
Размерность гистограммы частот 
.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB45\fP
.SS "long [] MihStatLibrary\&.Histogram\&.FreqHistogram\&.Histogram\fR [get]\fP"

.PP
Гистограмма частот 
.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB40\fP
.SS "long MihStatLibrary\&.Histogram\&.FreqHistogram\&.NmVectors\fR [get]\fP"

.PP
Количество учтенных последовательностей 
.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB50\fP
.SS "int MihStatLibrary\&.Histogram\&.FreqHistogram\&.SzShift\fR [get]\fP"

.PP
Смещение гистограммы частот 
.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB55\fP
.SH "Cобытия"
.PP 
.SS "EventHandler<string>? MihStatLibrary\&.Histogram\&.FreqHistogram\&.ProcessChanged = null"

.PP
Событие изменения процесса обсчитывания 
.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB30\fP
.SS "EventHandler<int>? MihStatLibrary\&.Histogram\&.FreqHistogram\&.ProgressChanged = null"

.PP
Событие изменения прогресса обсчитывания 
.PP
См\&. определение в файле \fBFreqHistogram\&.cs\fP строка \fB35\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
