.TH "MihStatLibrary.BlockData.IBlockDataSource" 3 "Version 1.0" "MihStatLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MihStatLibrary.BlockData.IBlockDataSource \- Интерфейс источника получения блока данных  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBMihStatLibrary\&.BlockData\&.BlockDataFileSource\fP и \fBMihStatLibrary\&.BlockData\&.BlockDataRandomSource\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "byte[] \fBGetBlockData\fP (int szBlock)"
.br
.RI "Заполняет блок данными из источника "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс источника получения блока данных 
.PP
См\&. определение в файле \fBIBlockDataSource\&.cs\fP строка \fB12\fP
.SH "Методы"
.PP 
.SS "byte[] MihStatLibrary\&.BlockData\&.IBlockDataSource\&.GetBlockData (int szBlock)"

.PP
Заполняет блок данными из источника 
.PP
\fBАргументы\fP
.RS 4
\fIszBlock\fP Размер запрашиваемого блока данных в байтах
.RE
.PP

.PP
Замещается в \fBMihStatLibrary\&.BlockData\&.BlockDataFileSource\fP и \fBMihStatLibrary\&.BlockData\&.BlockDataRandomSource\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для MihStatLibrary из исходного текста\&.
